---
name: Ruby
on: [push, pull_request]
jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: run script
        run: ruby test.rb
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1','head','jruby','jruby-head']
